[package]
name = "slint_example"
version = "0.1.0"

build = "src/build.rs"

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.4.1"

[build-dependencies]
slint-build = "1.4.1"
