import {CheckBox} from "std-widgets.slint";

export component CreateButton inherits Rectangle {
    Image {
        source: @image-url("../image/plus.svg");

        colorize: black;

        width: root.width;
        height: root.height;
    }

    TouchArea {
        clicked => {
            // Delegate to the user of this element
            root.clicked();
        }
    }

    width: 18px;
    height: 18px;

    callback clicked;
}

export component DeleteButton inherits Rectangle {
    Image {
        source: @image-url("../image/delete.svg");

        colorize: black;

        width: root.width;
        height: root.height;
    }

    TouchArea {
        clicked => {
            // Delegate to the user of this element
            root.clicked();
        }
    }

    in property <length> len_root_width;

    callback clicked;

    width: 18px;
    height: 18px;

    x: len_root_width - (self.width + 5px);
    y: 5px;
}

export component TickBox inherits CheckBox {
    /*TouchArea {
        clicked => {
            root.is_checked = !root.is_checked;
        }
    }*/

    accessible-role: checkbox;

    callback clicked;

    in property <bool> is_checked: false;

    width: 18px;
    height: 18px;
}

export component MoveButton inherits Rectangle {
    Image {
        source: @image-url("../image/move.png");

        colorize: black;

        width: root.width;
        height: root.height;
    }

    width: 18px;
    height: 18px;
}
