import {ScrollView, ListView} from "std-widgets.slint";

import {CheckableItem, Checklist, ChecklistContainer} from "checklist_components.slint";
import {Title} from "text_components.slint";
import {CreateButton, DeleteButton, TickBox, MoveButton} from "button_components.slint";

struct ChecklistInfo {str_title: string}
struct CheckableItemInfo {}

export component ChecklistApp inherits Window {
    property <length> len_width: 512px;
    property <length> len_height: 512px;

    width: len_width;
    height: len_height;

    in-out property <[ChecklistInfo]> arr_checklist;
    in-out property <[CheckableItemInfo]> arr_checkable_item;

    container := ChecklistContainer {
        len_root_width: len_width;
        len_root_height: len_height;

        VerticalLayout {
            HorizontalLayout {
                CreateButton {}
                Title {text: "Checklist App";}
                DeleteButton {len_root_width: root.width;}

                padding: 6px;
            }
            ScrollView {
                //width: root.width;
                VerticalLayout {
                    for current[i] in arr_checklist : HorizontalLayout {
                        alignment: center;
                        check := Checklist {
                            len_root_width: container.width;
                            len_root_height: container.height;

                            VerticalLayout {
                                HorizontalLayout {
                                    CreateButton {}
                                    Title {text: current.str_title;}
                                    DeleteButton {len_root_width: check.width;}

                                    padding: 6px;
                                }
                                ScrollView {
                                    //width: root.width;
                                    /*VerticalLayout {
                                        for i in arr_checklist : HorizontalLayout {
                                            alignment: center;
                                            Checklist {
                                                len_root_width: root.width;
                                                len_root_height: root.height;

                                            }
                                        }
                                    }*/
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
