import "../../font/RobotoMono-Regular.ttf";

import { CheckBox, ScrollView } from "std-widgets.slint";
component Title inherits Text {
    font-family: "Roboto Mono";
    font-size: 18px;

    color: black;

    y: 5px;

    horizontal-alignment: center;
}

component CreateButton inherits Rectangle {
    Image {
        source: @image-url("../image/plus.svg");

        colorize: black;

        width: root.width;
        height: root.height;
    }

    width: 18px;
    height: 18px;

    x: 5px;
    y: 5px;
}

component DeleteButton inherits Rectangle {
    Image {
        source: @image-url("../image/delete.svg");

        colorize: black;

        width: root.width;
        height: root.height;
    }

    in property <length> len_root_width;

    width: 18px;
    height: 18px;

    x: len_root_width - (self.width + 5px);
    y: 5px;
}

component TickBox inherits CheckBox {
    accessible-role: checkbox;

    width: 18px;
    height: 18px;
}
component TextBox inherits Rectangle {
    TextInput {
        font-family: "Roboto Mono";
        font-size: 18px;

        color: black;

        width: 100%;
        height: 100%;

        padding: 12px;

        horizontal-alignment: left;
        vertical-alignment: center;
    }

    preferred-width: 100%;
    height: 95%;

    background: white;

    border-color: black;
    border-width: 1px;
    border-radius: 6px;
}

component CheckableItem inherits Rectangle {
    in property <length> len_root_width;

    width: len_root_width - 32px;
    height: 32px;

    background: white;

    border-color: black;
    border-width: 1px;
    border-radius: 6px;

    VerticalLayout {
        alignment: center;

        HorizontalLayout {
            TickBox {}

            HorizontalLayout {
                TextBox {}

                padding-left: 6px;
                padding-right: 6px;
                padding-top: -4px;
                padding-bottom: -4px;
            }

            DeleteButton {len_root_width: root.width;}

            padding: 6px;
        }
    }
}

component Checklist inherits Rectangle {
    in property <length> len_root_width;
    in property <length> len_root_height;

    in property <string> str_title;

    width: len_root_width - 32px;
    height: len_root_height - 64px;

    background: white;

    border-color: black;
    border-width: 1px;
    border-radius: 6px;

    VerticalLayout {
        // Top Bar
        HorizontalLayout {
            CreateButton {}
            Title {text: str_title;}
            DeleteButton {len_root_width: root.width;}

            padding: 6px;
        }
        // Main Content
        ScrollView {
            // background shape
            Rectangle {
                width: root.width;
                height: root.height;

                background: white;
            }

            // Vertical layout helps maintain a stack
            VerticalLayout {
                //Horizontal layout allows the alignment attribute to be assigned to the checkable item.
                HorizontalLayout {
                    alignment: center;
                    CheckableItem {len_root_width: root.width;}
                }
                HorizontalLayout {
                    alignment: center;
                    CheckableItem {len_root_width: root.width;}
                }
                HorizontalLayout {
                    alignment: center;
                    CheckableItem {len_root_width: root.width;}
                }
                HorizontalLayout {
                    alignment: center;
                    CheckableItem {len_root_width: root.width;}
                }
            }
        }
    }
}

component ChecklistContainer inherits Rectangle {
    in property <length> len_root_width;
    in property <length> len_root_height;

    width: len_root_width - 32px;
    height: len_root_height - 32px;

    background: white;

    border-color: black;
    border-width: 1px;
    border-radius: 6px;

    VerticalLayout {
        // Top Bar
        HorizontalLayout {
            CreateButton {}
            Title {text: "Checklist App";}
            DeleteButton {len_root_width: root.width;}

            padding: 6px;
        }
        // Main Content
        ScrollView {
            // background shape
            Rectangle {
                width: root.width;
                height: root.height;

                background: white;
            }

            // Vertical layout helps maintain a stack
            VerticalLayout {
                //Horizontal layout allows the alignment attribute to be assigned to the checkable item.
                HorizontalLayout {
                    alignment: center;

                    Checklist {
                        len_root_width: root.width;
                        len_root_height: root.height;

                        padding: 16px;

                        str_title: "Checklist 1";
                    }
                }
                HorizontalLayout {
                    alignment: center;

                    Checklist {
                        len_root_width: root.width;
                        len_root_height: root.height;

                        padding: 16px;

                        str_title: "Checklist 2";
                    }
                }
            }
        }
    }
}

export component ChecklistApp inherits Window {
    property <length> len_width: 512px;
    property <length> len_height: 512px;

    width: len_width;
    height: len_height;

    ChecklistContainer{
        len_root_width: root.len_width;
        len_root_height: root.len_height;
    }
}
