import "../../font/RobotoMono-Regular.ttf";

export component Title inherits Text {
    font-family: "Roboto Mono";
    font-size: 18px;

    color: black;

    y: 5px;

    horizontal-alignment: center;
}

export component TextBox inherits Rectangle {
    TextInput {
        font-family: "Roboto Mono";
        font-size: 18px;

        color: black;

        width: 100%;
        height: 100%;

        padding: 12px;

        horizontal-alignment: left;
        vertical-alignment: center;
    }

    preferred-width: 100%;
    height: 95%;

    background: white;

    border-color: black;
    border-width: 1px;
    border-radius: 6px;
}
